# -*- coding: utf-8 -*-
"""Customer Churn Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYJaKiCK3ztGenjRGJiDtNnwxxu7QUWN
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv('/content/drive/MyDrive/Telco_Customer_Churn_Dataset  (2).csv')

data.shape

pd.set_option("display.max_columns",None)

data.head()

data.info()



data.describe()

data.columns

data.duplicated().sum()

data.drop(['customerID','Partner','Dependents','SeniorCitizen'],axis=1, inplace=True)

data.head()

plt.figure(figsize=(10,6))
sns.scatterplot(x=data['tenure'], y=data['MonthlyCharges'], hue=data['Churn'])
plt.title('Employee Tenure vs Monthly Charges')
plt.show()

sns.countplot(x=data['Churn'], hue=data['Churn'])
plt.ylabel('No.of Employee')
plt.title('Employee Churn')
plt.show()

sns.lineplot(x=data['Contract'],y=data['MonthlyCharges'],hue=data['Churn'])
plt.title('Contract vs Monthly Charges of Employee')
plt.show()